spring:

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 100MB


  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/ecommerce?serverTimezone=Asia/Seoul
    username: yj
    password: kkt1326!

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        #jdbc.time_zone: UTC
    show-sql: true

#  security:
#    user:
#      name: admin
#      password: 1234
#      roles: ADMIN



logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor.sql: trace

#  org.hibernate.type: trace