spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 100MB

  mustache:
    prefix: classpath:/templates/
    suffix: .html
    charset: utf-8
    servlet:
      content-type: text/html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce
    username: yj
    password: kkt1326!

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 59063304683-j0j38mi2uv8ral82al9765ppc0n0eb96.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile

#  security:
#    user:
#      name: admin
#      password: 1234
#      roles: ADMIN

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace


server:
  servlet:
    encoding:
      force-response: true